travis:
  secure:
    BINSTAR_TOKEN: aLmi2u9jcP5wHp5dEsT0LIunq+kLC6cWyvNlrjuYW9YQk13Xah7Y1s3sVmn1Zrgy/6exWNuYPsNuzkrHsevsGxlYH4Wavj6M/NqpNeQGCvQbkItJ7nCpDlXXqBjxpWmXryfRhcdIvhWvGGYR+PW9ZhT0rab7piEXNG1u1WAjIBsSqCSQZ1t1TiIh1FRkiYTHc92hFqUXr9ALxkSJHjoi0dJCv8/vYRq33vyKiguokTMEdh7z7/SYuKSYxtN+uGa8sJ/N80Zm1ZDM/Mtt/+IfEkoiuPBqrXwpTytACm2Dmbj5VoOipRopkombjXke49sH0ERBRAXlbiEJ4Hms9yrorwiVNWoAOGPwg2yADPWPqG+Wl8cUQpoqcQjYxbbgX1vbuYur+lOchie6oICwAeFgktY7HKYxkiczfsZxTGg+pv5gXE/SGRFOogS4NadPSg8ytWFYB7eXOjr7el3QXis40AKZ+cCKbGWIPavCZMe9G5myWMOb++GVeKSlb4fY3pTSLlDFsz75vl5TSanpqq+5Nmw+ahvGxEf4rHBAdLrq2edBJwTz11yYAII5o9XIXDTaH4k94eNRf8uC/Q4q/mt8sLZOMzfSE80wjLMLqNAQTPtH4C1dzzOAuGy+KmxqQVIYvsMU5TBQhALlL3D0RFYYx8kro84HV8TCJSQRrC12Qbw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
