travis:
  secure:
    BINSTAR_TOKEN: 0JrB5K+HIVNAIu8k03x5ObATa0f2BBU+VQhOwLmNqHO0tOq0DRxYeZzC+Tr3wY7aEBPr9i+nJsDyNB6/C7EU6SCbhxsI8GDdJp18YsvfU+fSlYv6oBR2VbowBD2aKKF1tnD3PXyHTE9+VIN/C+Y0RLhEFYSbA/Z544DZDBXeXD+8e20llqryGi4BMoK9HU+4Uqwyfrbnv0/Hbe9tzFyHeggJ4simizg6seP9gE9x/1sKRLhLduFW3Df2a9yLr+1wqqRXYWSZVAidlfSFUHf0sawRTnMmBDvLc8oZDK2N3ItsMCAFZ+UaMsyrz9gwHmo+5D12s4cYlXpfT7rq40kSXu4WZZ2AufuSbDB1stVwduusgC58WUM9ic9hc0tSTM8/h1erQCfMgfjQksZK4UMXKFCZbiGUvG3DSFiB49QI+MqkOv9//D3p2usVHWq5clRIhAHs9eWTOeGYPbeR9qJWFrAq+XedTIpJt6EkIDWimhDqAUVznhRbI6UJ7VIQFNTShNVbTO+Ajy57+JoZ2UsSnFcD6uhut2mD81O5MBALdPCuokZy4AHVuVUXQfDp6UkDJgHjpvpGaFwQfQQ0yGn37xQ3mI99VVxSSKNB+0pNvwiuF00Cjs9mYhM/RP6NHxlsC09/RFJA++4YWrP8YKYES5E/OBEjPI1ey0tXtXnqNdE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
