travis:
  secure:
    BINSTAR_TOKEN: FvFhp8c62carI5qB8T8gnfS6129V728YmJBIP8Or2ftYyrvtQjEiaJ7usJc9g45PGDVOGrb/BoEtub9CpbfRhDDhPvl+Sm9Q8kZjgEcLI4ByrY3JEw+UTkyx6u4kdZmfyDns7yWZ+8MgUoQ9uMcO30MZC4fydNKY6dcyCGAOH8Wr6cA6F6MKKtPO06G6ZioywEIhb7V7xltJmuUTOFwl7bPTl29J9HF8WUKLWn6ACskIMuuRXuQAPQnFxc/klL1OopWlfNMYgRodDNAlaXFtgx0ytl6QOy9G4e3Ual0Z4NG2/QgcuPNWuT3aNXZpd3MYPQGU2PiOj0M78hV6lR2KNioLrEbCMSuVJOx66J827wAOo/2H8fi0F7TuFI5ZGeexjpzCI+9DaGEu4sKvLlasQrCKYfWq60K8MueGvl694/5Dp7E7h1c9X6q/5/sKbDTOqER8c2FDuEsTP7hPhRIPpwl5wrpJ3vWHwwUcT0jFqctfu2MP49wdmNdRJ1R/CYjxAuAq3FxJwO/Ldaak/fpWTtZbCa+Mfo0daLwp5WySxwFkc9JgaV1WgkakKLTmdRyFRb9+kPgStpnURO+m9A7rRuOPIY62gz+fySZtzIlmHIJYpMozCapzLMLsK44eHQV2DHz+w4z9jIpLCTD0jXm9VbFFrYtMIsHqfXDss30XTiI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
